package com.tianm.domain;


import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by SunYi on 2016/3/24/0024.
 */

@Entity
@Table(name = "users")
public class User {
    // ==============
    // PRIVATE FIELDS
    // ==============
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    // The user email
    @NotNull
    private String email;
    // The user name
    private String name;

    private String password;

    // ==============
    // PUBLIC METHODS
    // ==============
    public User() {
    }


    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
} // class User

